meal_plans/urls.py
from django.urls import path

from meal_plans.views import (
    PlanListView,
    PlanCreateView,
    PlanDeleteView,
    PlanDetailView,
    PlanUpdateView,
)

urlpatterns = [
    path("", PlanListView.as_view(), name="meal_plans_list"),
    path(
        "<int:pk>/",
        PlanDetailView.as_view(),
        name="meal_plans_detail",
    ),
    path(
        "<int:pk>/edit",
        PlanUpdateView.as_view(),
        name="meal_plans_edit",
    ),
    path(
        "<int:pk>/delete/",
        PlanDeleteView.as_view(),
        name="meal_plans_delete",
    ),
    path("create/", PlanCreateView.as_view(), name="meal_plans_new"),
]

scrumptious/urls.py
from django.contrib import admin
from django.urls import include, path, reverse_lazy
from django.views.generic.base import RedirectView
from django.contrib.auth import views as auth_views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("recipes/", include("recipes.urls")),
    path("tags/", include("tags.urls")),
    path(
        "",
        RedirectView.as_view(url=reverse_lazy("recipes_list")),
        name="home",
    ),
    path("accounts/login/", auth_views.LoginView.as_view(), name="login"),
    path("accounts/logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("meal_plans/", include("meal_plans.urls")),
]

tags/urls.py
from django.urls import path

from tags.views import (
    TagCreateView,
    TagDeleteView,
    TagDetailView,
    TagListView,
    TagUpdateView
)

urlpatterns = [
    path("", TagListView.as_view(), name="tag_list"),
    path("<int:pk>/delete/", TagDeleteView.as_view(), name="tag_delete"),
    path("new/", TagCreateView.as_view(), name="tag_new"),
    path("<int:pk>/edit/", TagUpdateView.as_view(), name="tag_edit"),
    path("<int:pk>/", TagDetailView.as_view(), name="tag_detail"),
]

meal_plans/models.py
from django.db import models
from django.conf import settings

USER_MODEL = settings.AUTH_USER_MODEL


# Create your models here.
class MealPlan(models.Model):
    name = models.CharField(max_length=125)
    date = models.DateField(null=True)
    owner = models.ForeignKey(
        USER_MODEL,
        related_name="mealplans",
        on_delete=models.CASCADE,
        null=True,
    )
    recipes = models.ManyToManyField("recipes.Recipe", related_name="recipe")

    def __str__(self):
        return self.name + " by " + str(self.owner)

meal_plans/views.py
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin

from meal_plans.models import MealPlan

# from recipes.forms import RecipeForm

# Create your views here.


class PlanListView(LoginRequiredMixin, ListView):
    model = MealPlan
    template_name = "meal_plans/list.html"
    paginate = 2

    def get_queryset(self):
        return MealPlan.objects.filter(name=self.request)


class PlanCreateView(LoginRequiredMixin, CreateView):
    model = MealPlan
    template_name = "meal_plans/new.html"
    fields = ["name", "date", "recipes"]
    success_url = reverse_lazy("meal_plans_detail")

    def form_valid(self, form):
        plan = form.save(commit=False)
        plan.owner = self.request.user
        plan.save()
        form.save_m2m()
        return redirect("meal_plans_detail", pk=plan.id)


class PlanDetailView(LoginRequiredMixin, DetailView):
    model = MealPlan
    template_name = "meal_plans/detail.html"

    def get_queryset(self):
        return MealPlan.objects.filter(owner=self.request.user)


class PlanUpdateView(LoginRequiredMixin, UpdateView):
    model = MealPlan
    template_name = "meal_plans/edit.html"
    fields = ["name", "date", "recipes"]

    def get_queryset(self):
        return MealPlan.objects.filter(owner=self.request.user)

    def get_success_url(self) -> str:
        return reverse_lazy("meal_plans_detail", args=[self.object.id])


class PlanDeleteView(LoginRequiredMixin, DeleteView):
    model = MealPlan
    template_name = "meal_plans/delete.html"
    success_url = reverse_lazy("meal_plans_list")

    def get_queryset(self):
        return MealPlan.objects.filter(owner=self.request.user)

meal_plans/templates/meal_plans/delete.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Edit {{ recipe.name }} - Scrumptious</title>
        <link rel="stylesheet" href="{% static 'css/app.css' %}">
    </head>
    <body>
        <header>
            <nav>
                <ul>
                    <li>
                        <a href="{% url 'home' %}">Scrumptious</a>
                    </li>
                    <li>
                        <a href="{% url 'admin:index' %}">Admin</a>
                    </li>
                    <li>
                        <a href="{% url 'recipe_new' %}">Write a recipe</a>
                    </li>
                </ul>
            </nav>
        </header>
        <main>
            <form method="post">
                {% csrf_token %}
                <p>
                    Are you sure you want to delete "{{ recipe }}"?
                </p>
                {{ form.as_p }}
                <div class="control">
                    <button class="button">Delete</button>
                </div>
            </form>
        </main>
    </body>
</html>

meal_plans/templates/meal_plans/detail.html
{% extends 'base.html' %}
{% load static %}
{% load markdownify %}
{% block content %}
    <main class="recipe-detail">
        <div>
            <a href="{% url 'meal_plans_edit' mealplan.id %}">| Edit |</a>
            <a href="{% url 'meal_plans_delete' mealplan.id %}">Delete</a>
            <a href="{% url 'meal_plans_new' %}">| Add New Meal Plan! |</a>
        </div>
        <h1>{{ mealplan.name }}</h1>
        <h2>by: {{ mealplan.owner | default_if_none:"Unknown" }}</h2>
        <p>
            {{ recipe.created }}
        </p>
        {{ meal_plans.description | markdownify }}
    </main>
{% endblock content %}

meal_plans/templates/meal_plans/edit.html
{% extends 'base.html' %}
{% block content %}
    <main class="recipe-form">
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <div class="control">
                <button class="button">Update!</button>
            </div>
        </form>
    </main>
{% endblock content %}

meal_plans/templates/meal_plans/list.html
{% extends 'base.html' %}
{% block content %}
    <main class="recipe-grid">
        {% for mealplan in mealplan_list %}
            <div class="recipe-card">
                <h2 class="recipe-card-title">
                    <a href="{% url 'meal_plan_detail' mealplan.pk %}">{{ mealplan.name }}</a>
                </h2>
                <p class="recipe-card-date">
                    {{ recipe.updated }}
                </p>
            </div>
        {% endfor %}
        <div>
            <li>
                <a href="{% url 'meal_plans_new' %}">Create a Meal Plan?</a>
            </li>
        </div>
    </main>
{% endblock content %}
{% block pagination %}
    <div class="pagination">
        <span class="step-links">
            {% if page_obj.has_previous %}
                <a href="?page=1">&laquo; first</a>
                <a href="?page={{ page_obj.previous_page_number }}">previous</a>
            {% endif %}
            <span class="current">Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.</span>
            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">next</a>
                <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
        </span>
    </div>
{% endblock pagination %}

meal_plans/templates/meal_plans/new.html
{% extends 'base.html' %} {% load static %} {% block content %}
<main class="recipe-form">
  <form method="post">
    {% csrf_token %} {{ form.as_p }}
    <div class="control">
      <button class="button">Create</button>
    </div>
  </form>
</main>
{% endblock content %}